name: "Build"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Web App
        run: |
          npm install
          npm run build

      - name: Archive dist folder
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
